# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Carson Life
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my website, where I post probably not 
  exciting things about my life and other stuff 
  totally unrelated to it. Thank you for coming.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.carsonlife.ca" # the base hostname & protocol for your site
twitter_username: Don't have one suckers
github_username:  leocarson

# Build settings
markdown: kramdown
